version : '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-ui
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"