FROM node:18.0 As builder

RUN npm install -g @angular/cli
WORKDIR /usr/src/app
COPY bank-app-ui/package*.json ./
RUN npm install
COPY bank-app-ui/. .

RUN ["npm", "run", "build", "--prod"]

FROM nginx:1.21.6-alpine

COPY --from=builder /usr/src/app/dist/bank-ui/ /usr/share/nginx/html
